apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-d
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: redis
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-controller
          image: nginx
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
  replicas: 3
  selector:
    matchLabels:
      type: front-end