apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    name: webapp-pod
spec:
  containers:
  - name: webapp-color
    image: kodekloud/simple-webapp-mysql
    resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
    envFrom:
      - secretRef:
          name: db-secret
    volumes:
      - name: app-secret-volume
        secret:
          secretName: app-secret
    env:
      - name: test
        value: test_value
      - name: db_password
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: DB_PASSWORD