apiVersion: v1
kind: Pod
metadata:
  name: red
  labels:
    app: myapp
spec:
  containers:
  - name: red
    image: nginx
    ports:
      - containerPort: 80
    resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
  initContainers:
  - name: init-myservice1
    image: busybox:1.28
    command: ['sh', '-c', 'sleep 2;']
  - name: init-myservice2
    image: busybox:1.28
    command: ['sh', '-c', 'sleep 3;']
  

